"""Per-account catalogue of Orion subscription-page HTML files (Ф5).

Orion ships the subscription page as ONE build-less `index.html`, volume-mounted
into the `remnawave/subscription-page` container. This store keeps a per-account
catalogue of such pages: each page's HTML lives at
`accounts/<id>/subpages/<page_id>.html`; a sibling `index.json` holds the
metadata list `[{id, name, size, created_at}]` (no HTML, so listing is cheap).

The account is resolved from the `current_account` ContextVar (set per-request by
`require_account`); background callers with no request context pass an explicit
`account_id`. Each HTML file is written atomically (temp file + `os.replace`);
the `index.json` read-modify-write is serialised under a process-wide lock so two
concurrent uploads can't lose each other's entry (a lost-update the plain
`write_text` in the other JSON stores is exposed to).
"""

from __future__ import annotations

import hashlib
import io
import json
import re as _re
import shutil
import threading
import time
import uuid
import zipfile
from pathlib import Path
from typing import Optional

from app.services import accounts

# Orion is a single static index.html; a comfortable ceiling that still rejects
# accidental multi-MB uploads. Enforced here (defensive) AND in the route (413).
MAX_HTML_BYTES = 512 * 1024  # 512 KiB
# Cap the per-account catalogue so an authenticated account can't fill the disk
# with 512 KiB pages without bound.
MAX_PAGES = 100

# Serialises index.json read-modify-write across threads (add/delete run in a
# threadpool via FastAPI's sync-to-thread offloading).
_INDEX_LOCK = threading.Lock()


def _dir(account_id: Optional[str]) -> Path:
    aid = account_id or accounts.current_account.get()
    if not aid:
        raise RuntimeError("No active account in context")
    d = accounts.data_dir(aid) / "subpages"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _index_path(account_id: Optional[str]) -> Path:
    return _dir(account_id) / "index.json"


def _read_index(account_id: Optional[str]) -> list[dict]:
    path = _index_path(account_id)
    try:
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            return data if isinstance(data, list) else []
    except Exception:
        pass
    return []


def _write_atomic(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _write_index(account_id: Optional[str], entries: list[dict]) -> None:
    _write_atomic(
        _index_path(account_id),
        json.dumps(entries, ensure_ascii=False, indent=2),
    )


def list_pages(account_id: Optional[str] = None) -> list[dict]:
    return _read_index(account_id)


def get_page_html(page_id: str, account_id: Optional[str] = None) -> Optional[str]:
    # Gate on index membership BEFORE touching the filesystem: page ids are
    # 12-hex generated by us, so a traversal/garbage id can never match — this
    # keeps `_dir / f"{page_id}.html"` from ever escaping the account dir.
    if not any(e["id"] == page_id for e in _read_index(account_id)):
        return None
    try:
        return (_dir(account_id) / f"{page_id}.html").read_text(encoding="utf-8")
    except Exception:
        return None


def add_page(name: str, html: str, account_id: Optional[str] = None) -> dict:
    name = (name or "").strip()
    if not name:
        raise ValueError("Имя страницы не может быть пустой")
    if not (html or "").strip():
        raise ValueError("HTML страницы не может быть пустым")
    size = len(html.encode("utf-8"))
    if size > MAX_HTML_BYTES:
        raise ValueError(
            f"HTML превышает лимит {MAX_HTML_BYTES} байт (получено {size})"
        )
    page_id = uuid.uuid4().hex[:12]
    entry = {
        "id": page_id,
        "name": name,
        "size": size,
        "created_at": int(time.time()),
    }
    with _INDEX_LOCK:
        entries = _read_index(account_id)
        if len(entries) >= MAX_PAGES:
            raise ValueError(f"Достигнут лимит страниц ({MAX_PAGES})")
        _write_atomic(_dir(account_id) / f"{page_id}.html", html)
        entries.append(entry)
        _write_index(account_id, entries)
    return entry


def delete_page(page_id: str, account_id: Optional[str] = None) -> bool:
    with _INDEX_LOCK:
        entries = _read_index(account_id)
        entry = next((e for e in entries if e["id"] == page_id), None)
        kept = [e for e in entries if e["id"] != page_id]
        if entry is None:
            return False
        _write_index(account_id, kept)
    if (entry.get("kind") or KIND_HTML) == KIND_OVERLAY:
        shutil.rmtree(_overlay_dir(page_id, account_id), ignore_errors=True)
        return True
    try:
        (_dir(account_id) / f"{page_id}.html").unlink()
    except FileNotFoundError:
        pass
    return True


# ══════════════════════════════════════════════════════════════
# Overlay variants (Wave-7 Plan G Ф5)
#
# A "variant" is a sparse tree of files that is laid OVER the baseline pulled
# out of the `remnawave/subscription-page` image, rather than a single HTML that
# replaces it. That is the whole reason this exists: mounting one index.html on
# top of the image silently destroyed the EJS template that feeds the SPA
# (Wave 6, Plan E Ф1).
#
# Legacy `kind: "html"` pages keep working untouched — `add_page`/`get_page_html`/
# `MAX_HTML_BYTES` above are deliberately not modified.
# ══════════════════════════════════════════════════════════════

KIND_HTML = "html"
KIND_OVERLAY = "overlay"

MAX_FILE_BYTES = 8 * 1024 * 1024        # a single asset (the image's largest is 300 KB)
MAX_VARIANT_BYTES = 32 * 1024 * 1024    # whole tree; the baseline itself is ~7 MB
MAX_FILES_PER_VARIANT = 400             # the 7.2.6 image ships 160

# Path charset for overlay members. Deliberately narrower than the filesystem
# allows: these names end up in a shell (`unzip` on the node) and in URLs.
_RELPATH_OK = _re.compile(r"^[A-Za-z0-9._/-]+$")
_MAX_RELPATH_LEN = 200
_MAX_RELPATH_DEPTH = 10


class RelPathError(ValueError):
    """Rejected overlay member path."""


def normalize_relpath(relpath: str) -> str:
    """Validate a member path and return it normalised (forward slashes, no
    leading slash).

    ⚠️ The index-membership guard that protects `page_id` does NOT help here:
    `relpath` is user-supplied and never generated by us. Every rejection below
    is load-bearing; `library_store`'s idiom cannot be copied because it
    sanitises a flat NAME, not a path.
    """
    # ⚠️ Deliberately NOT normalising `\` into `/`: reinterpreting a client's
    # path is how traversal guards get surprised. A backslash simply fails the
    # charset check below and the request is rejected.
    p = (relpath or "").strip()
    if not p:
        raise RelPathError("Пустой путь")
    if len(p) > _MAX_RELPATH_LEN:
        raise RelPathError(f"Путь длиннее {_MAX_RELPATH_LEN} символов")
    if p.startswith("/"):
        raise RelPathError("Путь должен быть относительным")
    if ":" in p:  # C:/... and alternate data streams
        raise RelPathError("Недопустимый символ ':' в пути")
    if not _RELPATH_OK.match(p):
        raise RelPathError("Путь содержит недопустимые символы")
    parts = p.split("/")
    if len(parts) > _MAX_RELPATH_DEPTH:
        raise RelPathError(f"Слишком глубокая вложенность (>{_MAX_RELPATH_DEPTH})")
    for seg in parts:
        if seg in ("", ".", ".."):
            raise RelPathError("Недопустимый сегмент пути")
    return p


def _overlay_dir(page_id: str, account_id: Optional[str] = None) -> Path:
    return _dir(account_id) / page_id


def _files_dir(page_id: str, account_id: Optional[str] = None) -> Path:
    return _overlay_dir(page_id, account_id) / "files"


def _manifest_path(page_id: str, account_id: Optional[str] = None) -> Path:
    # A sibling of the tree, not a field of index.json: the listing must stay
    # cheap (that is the reason index.json exists in the first place).
    return _overlay_dir(page_id, account_id) / "manifest.json"


def _resolved_member(page_id: str, relpath: str, account_id: Optional[str]) -> Path:
    """Defence in depth: even after `normalize_relpath`, prove the resolved path
    is inside the variant's own tree before touching it."""
    root = _files_dir(page_id, account_id).resolve()
    target = (root / normalize_relpath(relpath)).resolve()
    if root != target and root not in target.parents:
        raise RelPathError("Путь выходит за пределы варианта")
    return target


def _entry(page_id: str, account_id: Optional[str]) -> Optional[dict]:
    return next((e for e in _read_index(account_id) if e["id"] == page_id), None)


def _read_manifest(page_id: str, account_id: Optional[str]) -> list[dict]:
    try:
        data = json.loads(_manifest_path(page_id, account_id).read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except Exception:
        return []


def _write_manifest(page_id: str, files: list[dict], account_id: Optional[str]) -> None:
    _overlay_dir(page_id, account_id).mkdir(parents=True, exist_ok=True)
    _write_atomic(
        _manifest_path(page_id, account_id),
        json.dumps(files, ensure_ascii=False, indent=2),
    )


def _sync_entry(page_id: str, files: list[dict], account_id: Optional[str]) -> dict:
    """Refresh the index entry's counters from the manifest. Called under the lock.

    ⚠️ `size` is kept as a NUMBER even for overlays: the legacy catalogue screen
    renders `fmtSize(p.size)`, and `fmtSize(undefined)` prints 'NaN КиБ'."""
    total = sum(int(f.get("size", 0)) for f in files)
    entries = _read_index(account_id)
    out = None
    for e in entries:
        if e["id"] == page_id:
            e["files_count"] = len(files)
            e["bytes"] = total
            e["size"] = total
            out = e
    _write_index(account_id, entries)
    return out or {}


def add_overlay(
    name: str,
    base_image: str = "",
    base_digest: str = "",
    account_id: Optional[str] = None,
) -> dict:
    """Create an EMPTY overlay variant. Files arrive one by one via `put_file`."""
    name = (name or "").strip()
    if not name:
        raise ValueError("Имя варианта не может быть пустым")
    page_id = uuid.uuid4().hex[:12]
    entry = {
        "id": page_id,
        "name": name,
        "kind": KIND_OVERLAY,
        "base_image": base_image,
        "base_digest": base_digest,
        "files_count": 0,
        "bytes": 0,
        "size": 0,
        "created_at": int(time.time()),
    }
    with _INDEX_LOCK:
        entries = _read_index(account_id)
        if len(entries) >= MAX_PAGES:
            raise ValueError(f"Достигнут лимит страниц ({MAX_PAGES})")
        _files_dir(page_id, account_id).mkdir(parents=True, exist_ok=True)
        _write_manifest(page_id, [], account_id)
        entries.append(entry)
        _write_index(account_id, entries)
    return entry


def is_overlay(page_id: str, account_id: Optional[str] = None) -> bool:
    e = _entry(page_id, account_id)
    return bool(e) and (e.get("kind") or KIND_HTML) == KIND_OVERLAY


def list_files(page_id: str, account_id: Optional[str] = None) -> Optional[list[dict]]:
    """Manifest of the variant, or None when it isn't an overlay of this account."""
    if not is_overlay(page_id, account_id):
        return None
    return _read_manifest(page_id, account_id)


def put_file(
    page_id: str, relpath: str, data: bytes, account_id: Optional[str] = None
) -> dict:
    if not is_overlay(page_id, account_id):
        raise ValueError("Вариант не найден")
    rel = normalize_relpath(relpath)
    if len(data) > MAX_FILE_BYTES:
        raise ValueError(f"Файл больше лимита {MAX_FILE_BYTES} байт")

    with _INDEX_LOCK:
        files = _read_manifest(page_id, account_id)
        others = [f for f in files if f["path"] != rel]
        if len(others) >= MAX_FILES_PER_VARIANT:
            raise ValueError(f"Достигнут лимит файлов ({MAX_FILES_PER_VARIANT})")
        projected = sum(int(f.get("size", 0)) for f in others) + len(data)
        if projected > MAX_VARIANT_BYTES:
            raise ValueError(f"Вариант превысит лимит {MAX_VARIANT_BYTES} байт")

        target = _resolved_member(page_id, rel, account_id)
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp = target.with_name(target.name + ".tmp")
        tmp.write_bytes(data)
        tmp.replace(target)

        meta = {
            "path": rel,
            "size": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
            "updated_at": int(time.time()),
        }
        _write_manifest(page_id, others + [meta], account_id)
        _sync_entry(page_id, others + [meta], account_id)
    return meta


def get_file(
    page_id: str, relpath: str, account_id: Optional[str] = None
) -> Optional[bytes]:
    if not is_overlay(page_id, account_id):
        return None
    rel = normalize_relpath(relpath)
    if not any(f["path"] == rel for f in _read_manifest(page_id, account_id)):
        return None
    try:
        return _resolved_member(page_id, rel, account_id).read_bytes()
    except OSError:
        return None


def delete_file(page_id: str, relpath: str, account_id: Optional[str] = None) -> bool:
    if not is_overlay(page_id, account_id):
        return False
    rel = normalize_relpath(relpath)
    with _INDEX_LOCK:
        files = _read_manifest(page_id, account_id)
        kept = [f for f in files if f["path"] != rel]
        if len(kept) == len(files):
            return False
        try:
            _resolved_member(page_id, rel, account_id).unlink()
        except OSError:
            pass
        _write_manifest(page_id, kept, account_id)
        _sync_entry(page_id, kept, account_id)
    return True


def overlay_zip(page_id: str, account_id: Optional[str] = None) -> Optional[bytes]:
    """In-memory zip of ONLY the overlay's own files — this is what gets shipped
    to the node and unpacked over the materialised baseline."""
    if not is_overlay(page_id, account_id):
        return None
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in _read_manifest(page_id, account_id):
            data = get_file(page_id, f["path"], account_id)
            if data is not None:
                zf.writestr(f["path"], data)
    return buf.getvalue()
