"""Per-account catalogue of Orion subscription-page HTML files (Ф5).

Orion ships the subscription page as ONE build-less `index.html`, volume-mounted
into the `remnawave/subscription-page` container. This store keeps a per-account
catalogue of such pages: each page's HTML lives at
`accounts/<id>/subpages/<page_id>.html`; a sibling `index.json` holds the
metadata list `[{id, name, size, created_at}]` (no HTML, so listing is cheap).

The account is resolved from the `current_account` ContextVar (set per-request by
`require_account`); background callers with no request context pass an explicit
`account_id`. Each HTML file is written atomically (temp file + `os.replace`);
the `index.json` read-modify-write is serialised under a process-wide lock so two
concurrent uploads can't lose each other's entry (a lost-update the plain
`write_text` in the other JSON stores is exposed to).
"""

from __future__ import annotations

import json
import threading
import time
import uuid
from pathlib import Path
from typing import Optional

from app.services import accounts

# Orion is a single static index.html; a comfortable ceiling that still rejects
# accidental multi-MB uploads. Enforced here (defensive) AND in the route (413).
MAX_HTML_BYTES = 512 * 1024  # 512 KiB
# Cap the per-account catalogue so an authenticated account can't fill the disk
# with 512 KiB pages without bound.
MAX_PAGES = 100

# Serialises index.json read-modify-write across threads (add/delete run in a
# threadpool via FastAPI's sync-to-thread offloading).
_INDEX_LOCK = threading.Lock()


def _dir(account_id: Optional[str]) -> Path:
    aid = account_id or accounts.current_account.get()
    if not aid:
        raise RuntimeError("No active account in context")
    d = accounts.data_dir(aid) / "subpages"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _index_path(account_id: Optional[str]) -> Path:
    return _dir(account_id) / "index.json"


def _read_index(account_id: Optional[str]) -> list[dict]:
    path = _index_path(account_id)
    try:
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            return data if isinstance(data, list) else []
    except Exception:
        pass
    return []


def _write_atomic(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _write_index(account_id: Optional[str], entries: list[dict]) -> None:
    _write_atomic(
        _index_path(account_id),
        json.dumps(entries, ensure_ascii=False, indent=2),
    )


def list_pages(account_id: Optional[str] = None) -> list[dict]:
    return _read_index(account_id)


def get_page_html(page_id: str, account_id: Optional[str] = None) -> Optional[str]:
    # Gate on index membership BEFORE touching the filesystem: page ids are
    # 12-hex generated by us, so a traversal/garbage id can never match — this
    # keeps `_dir / f"{page_id}.html"` from ever escaping the account dir.
    if not any(e["id"] == page_id for e in _read_index(account_id)):
        return None
    try:
        return (_dir(account_id) / f"{page_id}.html").read_text(encoding="utf-8")
    except Exception:
        return None


def add_page(name: str, html: str, account_id: Optional[str] = None) -> dict:
    name = (name or "").strip()
    if not name:
        raise ValueError("Имя страницы не может быть пустой")
    if not (html or "").strip():
        raise ValueError("HTML страницы не может быть пустым")
    size = len(html.encode("utf-8"))
    if size > MAX_HTML_BYTES:
        raise ValueError(
            f"HTML превышает лимит {MAX_HTML_BYTES} байт (получено {size})"
        )
    page_id = uuid.uuid4().hex[:12]
    entry = {
        "id": page_id,
        "name": name,
        "size": size,
        "created_at": int(time.time()),
    }
    with _INDEX_LOCK:
        entries = _read_index(account_id)
        if len(entries) >= MAX_PAGES:
            raise ValueError(f"Достигнут лимит страниц ({MAX_PAGES})")
        _write_atomic(_dir(account_id) / f"{page_id}.html", html)
        entries.append(entry)
        _write_index(account_id, entries)
    return entry


def delete_page(page_id: str, account_id: Optional[str] = None) -> bool:
    with _INDEX_LOCK:
        entries = _read_index(account_id)
        kept = [e for e in entries if e["id"] != page_id]
        if len(kept) == len(entries):
            return False
        _write_index(account_id, kept)
    try:
        (_dir(account_id) / f"{page_id}.html").unlink()
    except FileNotFoundError:
        pass
    return True
