"""Ф4 (wave1) — Remnawave panel / subscription-page deploy routes — /api/panel.

  POST /api/panel/deploy   — install the panel and/or subscription page (streamed
                             Task; SSH creds transient, per-request).
  POST /api/panel/detect   — read-only probe of a live box (docker / panel /
                             subpage / test-tools present?). One SSH session.
  POST /api/panel/step     — per-component reinstall / uninstall against a live
                             box (streamed Task). Minimal skeleton — Ф7 fills the
                             full matrix.

SSH creds are passed per-request from the browser and NEVER persisted (same rule
as /api/node/step and /api/stats/node). Secrets generated by the pipeline
(JWT / PG / webhook) are written through `panel_pipeline`'s SILENT channel and are
never logged.
"""

from __future__ import annotations

import re
from typing import Literal, Optional

from fastapi import APIRouter, BackgroundTasks, HTTPException
from pydantic import BaseModel, Field, field_validator

from app.models.panel_deploy import PanelDeployRequest, SubServer
from app.services import panel_pipeline
from app.services.ssh_manager import SSHSession
from app.services.task_store import TaskStatus, task_store

router = APIRouter(prefix="/api/panel")


# ──────────────────────────────────────────────────────────────
# POST /api/panel/deploy — streamed install Task
# ──────────────────────────────────────────────────────────────


@router.post("/deploy")
async def panel_deploy(
    req: PanelDeployRequest, background_tasks: BackgroundTasks
) -> dict:
    """Kick off the panel / subpage install as a background Task; the browser
    subscribes to the log stream via /ws/logs/{task_id}."""
    task = task_store.create(total_steps=panel_pipeline.PANEL_TOTAL)
    background_tasks.add_task(panel_pipeline.run_panel_pipeline, req, task)
    return {"task_id": task.task_id, "task_type": "panel"}


# ──────────────────────────────────────────────────────────────
# POST /api/panel/detect — read-only component probe
# ──────────────────────────────────────────────────────────────

_DETECT_PRESENT = "NI_PRESENT"
_DETECT_ABSENT = "NI_ABSENT"


def _detect_cmd(test: str) -> str:
    """Wrap a read-only test command so it echoes a single-line sentinel."""
    return f"{test} && echo {_DETECT_PRESENT} || echo {_DETECT_ABSENT}"


def _parse_detect(out: str) -> str:
    """Map a probe's stdout to present|absent|unknown (last non-empty line wins,
    so leading warnings/motd don't confuse it; anything unexpected → unknown)."""
    lines = [ln.strip() for ln in (out or "").splitlines() if ln.strip()]
    last = lines[-1] if lines else ""
    if last == _DETECT_PRESENT:
        return "present"
    if last == _DETECT_ABSENT:
        return "absent"
    return "unknown"


# One read-only probe per detectable component (plain strings — the `{{.Names}}`
# double-braces are docker Go-template syntax, NOT format placeholders).
_PANEL_PROBES: dict[str, str] = {
    "docker": "command -v docker >/dev/null 2>&1",
    "panel": (
        "test -f /opt/remnawave/.env && "
        "docker ps --format '{{.Names}}' 2>/dev/null | grep -q remnawave-backend"
    ),
    "subpage": (
        "test -d /opt/remnawave-subpage || "
        "docker ps --format '{{.Names}}' 2>/dev/null | grep -q remnawave-subscription"
    ),
    # test_tools: iperf3 + either speedtest CLI (Ookla `speedtest` or the python
    # fallback `speedtest-cli` — Ф1 installs whichever works, accept both).
    "test_tools": (
        "command -v iperf3 >/dev/null 2>&1 && "
        "( command -v speedtest >/dev/null 2>&1 || command -v speedtest-cli >/dev/null 2>&1 )"
    ),
}


class PanelDetectRequest(BaseModel):
    """Creds-per-request body for the read-only panel probe. `sub_server` is
    accepted for forward-compat (separate subpage box) but the probe currently
    inspects the primary server only. Creds are transient (never persisted)."""

    ip: str
    ssh_user: str = "root"
    ssh_password: str = Field(..., min_length=1)
    ssh_port: int = Field(default=22, ge=1, le=65535)
    sub_server: Optional[SubServer] = None

    @field_validator("ip")
    @classmethod
    def _validate_ip(cls, v: str) -> str:
        if not re.fullmatch(r"^(\d{1,3}\.){3}\d{1,3}$", v) or any(
            int(p) > 255 for p in v.split(".")
        ):
            raise ValueError("Invalid IPv4 address")
        return v


@router.post("/detect")
async def panel_detect(req: PanelDetectRequest) -> dict:
    """Probe a live server (read-only) and report which panel components are
    installed. One SSH session; a per-probe failure degrades to 'unknown' (never
    500). A connection failure → 502 with a Russian message."""
    ssh = SSHSession(req.ip, req.ssh_port, req.ssh_user, req.ssh_password)
    try:
        try:
            await ssh.connect()
        except Exception as exc:
            raise HTTPException(
                status_code=502,
                detail=f"Не удалось подключиться к серверу {req.ip}:{req.ssh_port}: {exc}",
            )
        components: dict[str, str] = {}
        for name, test in _PANEL_PROBES.items():
            try:
                out = await ssh.get_output(_detect_cmd(test))
                components[name] = _parse_detect(out)
            except Exception:
                components[name] = "unknown"
        installed = (
            components.get("panel") == "present"
            or components.get("subpage") == "present"
        )
        return {"installed": installed, "components": components}
    finally:
        await ssh.close()


# ──────────────────────────────────────────────────────────────
# POST /api/panel/step — per-component reinstall / uninstall (streamed Task)
# ──────────────────────────────────────────────────────────────

Component = Literal["panel", "subpage", "docker", "test_tools", "reverse_proxy"]
Action = Literal["reinstall", "uninstall"]

_COMPONENT_LABEL: dict[str, str] = {
    "panel": "Панель Remnawave",
    "subpage": "Страница подписок",
    "docker": "Docker",
    "test_tools": "Тест-инструменты",
    "reverse_proxy": "Reverse-proxy",
}


class PanelOpRequest(PanelDeployRequest):
    """The full panel-deploy payload (so we can rebuild the exact install) + which
    component and action. Inherits PanelDeployRequest's validators, so a hostile
    field can't reach the reinstall scripts."""

    component: Component
    action: Action


# Uninstall scripts (idempotent, `|| true`-guarded). Data volumes are NOT removed
# by default — the panel's Postgres/Valkey data survives a `down`. docker /
# test_tools uninstall is intentionally absent (removing the engine or the shared
# toolkit is out of scope for this wave — Ф7).
_UNINSTALL_SCRIPTS: dict[str, str] = {
    "panel": (
        "if [ -d /opt/remnawave ]; then\n"
        "  cd /opt/remnawave && (docker compose down 2>/dev/null || docker-compose down 2>/dev/null || true)\n"
        "fi\n"
        'echo "[panel] Панель остановлена (данные в томах Postgres/Valkey сохранены)."\n'
    ),
    "subpage": (
        "if [ -d /opt/remnawave-subpage ]; then\n"
        "  cd /opt/remnawave-subpage && (docker compose down 2>/dev/null || docker-compose down 2>/dev/null || true)\n"
        "fi\n"
        'echo "[subpage] Страница подписок остановлена."\n'
    ),
    "reverse_proxy": (
        "systemctl stop caddy 2>/dev/null || true\n"
        "systemctl stop nginx 2>/dev/null || true\n"
        'echo "[proxy] Reverse-proxy остановлен."\n'
    ),
}


@router.post("/step")
async def panel_step(req: PanelOpRequest, background_tasks: BackgroundTasks) -> dict:
    task = task_store.create(total_steps=1)
    background_tasks.add_task(_run_panel_op, req, task.task_id)
    return {"task_id": task.task_id, "task_type": "panel-op"}


def _op_target(req: PanelOpRequest) -> tuple[str, str, str, int]:
    """Which box the op runs against: the separate subpage server for a subpage
    op when one is configured, else the primary server."""
    if req.component == "subpage" and req.sub_server is not None:
        s = req.sub_server
        return s.ip, s.ssh_user, s.ssh_password, s.ssh_port
    return req.ip, req.ssh_user, req.ssh_password, req.ssh_port


async def _run_panel_op(req: PanelOpRequest, task_id: str) -> None:
    task = task_store.get(task_id)
    if not task:
        return
    label = _COMPONENT_LABEL[req.component]
    verb = {"reinstall": "Переустановка", "uninstall": "Удаление"}[req.action]
    ip, user, pw, port = _op_target(req)
    ssh = SSHSession(ip, port, user, pw)
    try:
        task.set_step(1, TaskStatus.RUNNING)
        task.add_log(f"\x1b[1;36m[{verb}] {label} на {ip}\x1b[0m")
        task.add_log(f"Подключение к {ip}:{port}...")
        await ssh.connect()
        task.add_log("\x1b[32mПодключено.\x1b[0m")

        if req.action == "uninstall":
            await _panel_uninstall(ssh, task, req)
        else:
            await _panel_reinstall(ssh, task, req)

        task.finish(TaskStatus.SUCCESS)
        task.add_log(f"\n\x1b[1;32m✓ {verb}: {label} — готово.\x1b[0m")
    except Exception as exc:
        task.add_log(f"\n\x1b[1;31m✗ Ошибка: {exc}\x1b[0m")
        task.finish(TaskStatus.FAILED, str(exc))
    finally:
        await ssh.close()


async def _panel_reinstall(ssh: SSHSession, task, req: PanelOpRequest) -> None:
    """Re-run the pipeline's own install helper for the component (idempotent —
    an existing .env is preserved so panel secrets are never regenerated)."""
    c = req.component
    if c == "panel":
        await panel_pipeline._install_panel(ssh, task, req)
    elif c == "subpage":
        await panel_pipeline._install_subpage(
            ssh, task, req, separate=not panel_pipeline._subpage_bundled(req)
        )
    elif c == "docker":
        await panel_pipeline._install_docker(ssh, task)
    elif c == "test_tools":
        await panel_pipeline._install_test_tools(ssh, task, req)
    elif c == "reverse_proxy":
        await panel_pipeline._setup_reverse_proxy(
            ssh, task, req, panel_pipeline._proxy_targets(req, "panel")
        )


async def _panel_uninstall(ssh: SSHSession, task, req: PanelOpRequest) -> None:
    """Dedicated teardown script for the component (the pipeline has no uninstall
    path). All are idempotent — removing an absent component is a no-op."""
    script = _UNINSTALL_SCRIPTS.get(req.component)
    if script is None:
        raise RuntimeError(
            f"Удаление компонента «{_COMPONENT_LABEL[req.component]}» "
            f"не поддерживается в этой волне (будет добавлено в Ф7)."
        )
    await ssh.run_script(script, task, check=False, timeout=180)
